# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c585abd76a051b3a8ebcfed9890aff1ff9de149ad198e000316f2f750b1078fa929e3e63c3e7420cca64120754878a6a8f63fe3105e7ede4cdd0f2f620d2c9

test:
  secret_key_base: 5ffe31798670c2130c5b0168c5f2cef14096abedc73e23f0efbf948d610976cc543837382279e84d86bb804651f31736306451e24b3e116638cc76178d150eda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
